application: flickfaver
version: live
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets

- url: /javascripts
  static_dir: javascripts

- url: /api/.*
  script: api.py
  
- url: /task/.*
  script: tasks.py  
    
- url: /.*
  script: main.py
  
