application: flickfaver-v2
version: development-new
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: media/images/favicon.ico
  upload: media/images/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/deferred.py
  login: admin

- url: /images
  static_dir: media/images

- url: /stylesheets
  static_dir: media/stylesheets

- url: /javascripts
  static_dir: media/javascripts

- url: /task/.*
  script: tasks.py  
    
- url: /.*
  script: main.py
  
